
// File generated by Wsutil Compiler version 1.0095 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by Wsutil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from a WSDL file, the file may contain up to three 
// sets of C/C++ definitions. The first set consists of function declarations that can be 
// used in calling operations on a running web service from client applications. 
// The second set consists of callback declarations that can be used in the 
// implementation of web services.  
// The third set contains definitions C/C++ structures that are used for serialization of 
// C/C++ types to Schema types defined in the WSDL file.
//
// The set of function declarations for web services clients may contain the 
// following declaration: 
//
//    HRESULT WINAPI DefaultBinding_ICalculator_Add(
//       _In_ WS_SERVICE_PROXY* _serviceProxy,
//       _In_ int a, 
//       _In_ int b, 
//       _Out_ int* result, 
//       _In_ WS_HEAP* _heap,
//       _In_opt_ WS_CALL_PROPERTY* _callProperties,
//       _In_ const ULONG _callPropertyCount,
//       _In_opt_ const WS_ASYNC_CONTEXT*_asyncContext,
//       _In_opt_ WS_ERROR* _error);
//
// This function can be called from an application code to request ICalculator web 
// service to perform operation Add using two integers a and b as input data.
// Once the web service processes this request and sends the result back,
// the result is returned to the caller of this function in the "result" parameter.
// A WS_SERVICE_PROXY must be created using WsCreateServiceProxy() function
// before this proxy function can be invoked.
//
// The set of callbacks for implementation of web services may contain the following 
// definition of a callback: 
//
//    typedef HRESULT (CALLBACK* DefaultBinding_ICalculator_AddCallback) (
//       _In_ const WS_OPERATION_CONTEXT* _context,
//       _In_ int a, 
//       _In_ int b, 
//       _Out_ int* result, 
//       _In_ const WS_ASYNC_CONTEXT* _asyncContext,
//       _In_ WS_ERROR* _error); 
//
//    typedef struct DefaultBinding_ICalculatorFunctionTable 
//    {
//         DefaultBinding_ICalculator_AddCallback DefaultBinding_ICalculator_Add;
//    } DefaultBinding_ICalculatorFunctionTable;
//
// This definition can be used to implement a function that defines the Add operation 
// as a part of an ICalculator web service. Once this callback is implemented and 
// the web service is deployed and running, if a client applications attempts to 
// execute the operation Add, the implementation of this callback is called and 
// it receives two integers a and b as input data and it returns a third integer 
// that is the result of the operation. A WS_SERVICE_ENDPOINT must be filled out, 
// and its contract field set to instance of such a function table.  
// WsCreateServiceHost may then be used to register the endpoint as a service.
// 
// The set with definitions of C/C++ structures may contain a definition of the following 
// structure:
//    typedef struct ContactInfo 
//    {
//			WCHAR*  name;
//			WCHAR*  email;
//			__int64 contactID;
//	  } ContactInfo;
//
// This structure corresponds to the following complex type defined in the WSDL file:
//    <s:complexType name="ContactInfo">
//      <s:sequence>
//        <s:element minOccurs="1" maxOccurs="1" name="name" type="s:string" />
//        <s:element minOccurs="1" maxOccurs="1" name="email" type="s:string" />
//        <s:element minOccurs="1" maxOccurs="1" name="contactID" type="s:long" />
//      </s:sequence>
//    </s:complexType>
//
// For more information about content of this file, please see the documentation for
// Wsutil compiler.
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
// If Wsutil generates this file from a WSDL file and policy processing is enabled using
// policy switch, the file may contain declaration of functions that can be used 
// for creating a proxy to a web service or an endpoint of a web service. 
// For example, the file may contain declaration of the following function:
//
//    HRESULT DefaultBinding_ICalculator_CreateServiceProxy(
//    _In_ WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
//    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
//    _In_ const ULONG proxyPropertyCount,
//    _Outptr_ WS_SERVICE_PROXY** proxy,
//    _In_opt_ WS_ERROR* error);
//
// This function can be called from application code to create a service
// proxy object. A service proxy must be created before any request can be sent 
// to the web service.
//
// Also, the file may contain declaration of the following function:
//
//    HRESULT DefaultBinding_ICalculator_CreateServiceEndpoint(
//    _In_ WS_HTTP_SSL_BINDING_TEMPLATE* templateValue,
//    _In_opt_ WS_STRING address,
//    _In_opt_ struct DefaultBinding_ICalculatorFunctionTable* functionTable,
//    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
//    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
//    _In_ const ULONG endpointPropertyCount,
//    _In_ WS_HEAP* heap,
//    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
//    _In_opt_ WS_ERROR* error);
//
// This function can be used to create a Service Host object, which has to be 
// created before a web services starts receiving requests from its clients.
//
// For more information about content of this file, please see the documentation for
// Wsutil compiler.
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following client functions were generated:

//     MacStatsCollectionBinding_SendStatsSample
//     MacStatsCollectionBinding_CloseService

// The following server function tables were generated:

//     struct MacStatsCollectionBindingFunctionTable

// The following types were generated:

//     struct listOfStatsFloat32;
//     struct listOfStatsInt32;
//     struct SendStatsSampleRequest;
//     struct _WrapSendStatsSampleRequest;
//     struct _SendStatsSampleResponse;
//     struct _CloseServiceRequest;
//     struct _CloseServiceResponse;

// the following policy helpers were generated:

//  MacStatsCollectionBinding_CreateServiceProxy;
//  MacStatsCollectionBinding_CreateServiceEndpoint;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: MacStatsCollection_wsdl.globalTypes.listOfStatsFloat32
typedef struct listOfStatsFloat32 
{
    _Field_range_(1, 4294967295) unsigned int entryCount;
    _Field_size_(entryCount)struct listOfStatsFloat32_entry* entry; // 1..unbounded
} listOfStatsFloat32;

// typeDescription: n/a
typedef struct listOfStatsFloat32_entry 
{
    WCHAR* statName;
    float statValue;
    char quality;
} listOfStatsFloat32_entry;

// typeDescription: MacStatsCollection_wsdl.globalTypes.listOfStatsInt32
typedef struct listOfStatsInt32 
{
    _Field_range_(1, 4294967295) unsigned int entryCount;
    _Field_size_(entryCount)struct listOfStatsInt32_entry* entry; // 1..unbounded
} listOfStatsInt32;

// typeDescription: n/a
typedef struct listOfStatsInt32_entry 
{
    WCHAR* statName;
    int statValue;
    char quality;
} listOfStatsInt32_entry;

// typeDescription: MacStatsCollection_wsdl.globalTypes.SendStatsSampleRequest
typedef struct SendStatsSampleRequest 
{
    __int64 time;
    WCHAR* machine;
    _Field_range_(1, 4294967295) unsigned int statsFloat32Count;
    _Field_size_(statsFloat32Count)struct listOfStatsFloat32_entry* statsFloat32; // 1..unbounded
    _Field_range_(1, 4294967295) unsigned int statsInt32Count;
    _Field_size_(statsInt32Count)struct listOfStatsInt32_entry* statsInt32; // 1..unbounded
} SendStatsSampleRequest;

// typeDescription: n/a
typedef struct _WrapSendStatsSampleRequest 
{
    WCHAR* key;
    struct SendStatsSampleRequest* payload;
} _WrapSendStatsSampleRequest;

// typeDescription: n/a
typedef struct _SendStatsSampleResponse 
{
    BOOL status;
} _SendStatsSampleResponse;

typedef struct _CloseServiceRequest _CloseServiceRequest;

// typeDescription: n/a
typedef struct _CloseServiceResponse 
{
    BOOL status;
} _CloseServiceResponse;

////////////////////////////////////////////////
// Policy helper routines
////////////////////////////////////////////////

//  WS_CHANNEL_PROPERTY_ENCODING = WS_ENCODING_XML_UTF8,
//  WS_CHANNEL_PROPERTY_ADDRESSING_VERSION = WS_ADDRESSING_VERSION_TRANSPORT,
//  WS_ENVELOPE_VERSION = WS_ENVELOPE_VERSION_SOAP_1_2,
// client channel type: WS_CHANNEL_TYPE_REQUEST, service endpoint channel type: WS_CHANNEL_TYPE_REPLY

HRESULT MacStatsCollectionBinding_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error);

struct MacStatsCollectionBindingFunctionTable;
HRESULT MacStatsCollectionBinding_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct MacStatsCollectionBindingFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error);

////////////////////////////////////////////////
// Client functions definitions
////////////////////////////////////////////////

// operation: MacStatsCollectionBinding_SendStatsSample
HRESULT WINAPI MacStatsCollectionBinding_SendStatsSample(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_z_ WCHAR* key, 
    _In_ SendStatsSampleRequest* payload, 
    _Out_ BOOL* status, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error);

// operation: MacStatsCollectionBinding_CloseService
HRESULT WINAPI MacStatsCollectionBinding_CloseService(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Out_ BOOL* status, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error);

////////////////////////////////////////////////
// Service functions definitions
////////////////////////////////////////////////

typedef HRESULT (CALLBACK* MacStatsCollectionBinding_SendStatsSampleCallback) (
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_z_ WCHAR* key, 
    _In_ SendStatsSampleRequest* payload, 
    _Out_ BOOL* status, 
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error);

typedef HRESULT (CALLBACK* MacStatsCollectionBinding_CloseServiceCallback) (
    _In_ const WS_OPERATION_CONTEXT* _context,
    _Out_ BOOL* status, 
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error);

// binding: MacStatsCollectionBinding
typedef struct MacStatsCollectionBindingFunctionTable 
{
    MacStatsCollectionBinding_SendStatsSampleCallback MacStatsCollectionBinding_SendStatsSample;
    MacStatsCollectionBinding_CloseServiceCallback MacStatsCollectionBinding_CloseService;
} MacStatsCollectionBindingFunctionTable;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _MacStatsCollection_wsdl
{
    struct // globalTypes
    {
        // xml type: listOfStatsFloat32 ("http://assignment.crossover.com/")
        // c type: listOfStatsFloat32
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: MacStatsCollection_wsdl.globalTypes.listOfStatsFloat32
        WS_STRUCT_DESCRIPTION listOfStatsFloat32;
        
        // xml type: listOfStatsInt32 ("http://assignment.crossover.com/")
        // c type: listOfStatsInt32
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: MacStatsCollection_wsdl.globalTypes.listOfStatsInt32
        WS_STRUCT_DESCRIPTION listOfStatsInt32;
        
        // xml type: SendStatsSampleRequest ("http://assignment.crossover.com/")
        // c type: SendStatsSampleRequest
        // WS_TYPE: WS_STRUCT_TYPE
        // typeDescription: MacStatsCollection_wsdl.globalTypes.SendStatsSampleRequest
        WS_STRUCT_DESCRIPTION SendStatsSampleRequest;
        
    } globalTypes;
    struct // globalElements
    {
        // xml element: WrapSendStatsSampleRequest ("http://assignment.crossover.com/")
        // c type: _WrapSendStatsSampleRequest
        // elementDescription: MacStatsCollection_wsdl.globalElements.WrapSendStatsSampleRequest
        WS_ELEMENT_DESCRIPTION WrapSendStatsSampleRequest;
        
        // xml element: SendStatsSampleResponse ("http://assignment.crossover.com/")
        // c type: _SendStatsSampleResponse
        // elementDescription: MacStatsCollection_wsdl.globalElements.SendStatsSampleResponse
        WS_ELEMENT_DESCRIPTION SendStatsSampleResponse;
        
        // xml element: CloseServiceRequest ("http://assignment.crossover.com/")
        // c type: _CloseServiceRequest
        // elementDescription: MacStatsCollection_wsdl.globalElements.CloseServiceRequest
        WS_ELEMENT_DESCRIPTION CloseServiceRequest;
        
        // xml element: CloseServiceResponse ("http://assignment.crossover.com/")
        // c type: _CloseServiceResponse
        // elementDescription: MacStatsCollection_wsdl.globalElements.CloseServiceResponse
        WS_ELEMENT_DESCRIPTION CloseServiceResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION WrapSendStatsSampleRequest;
        WS_STRUCT_DESCRIPTION SendStatsSampleResponse;
        WS_STRUCT_DESCRIPTION CloseServiceRequest;
        WS_STRUCT_DESCRIPTION CloseServiceResponse;
    } externallyReferencedTypes;
    struct // messages
    {
        // message: SendStatsSampleRequestMessage
        // c type: _WrapSendStatsSampleRequest
        // action: "http://assignment.crossover.com/SendStatsSample"
        // messageDescription: MacStatsCollection_wsdl.messages.SendStatsSampleRequestMessage
        WS_MESSAGE_DESCRIPTION SendStatsSampleRequestMessage;
        
        // message: SendStatsSampleResponseMessage
        // c type: _SendStatsSampleResponse
        // action: ""
        // messageDescription: MacStatsCollection_wsdl.messages.SendStatsSampleResponseMessage
        WS_MESSAGE_DESCRIPTION SendStatsSampleResponseMessage;
        
        // message: CloseServiceRequestMessage
        // c type: _CloseServiceRequest
        // action: "http://assignment.crossover.com/CloseService"
        // messageDescription: MacStatsCollection_wsdl.messages.CloseServiceRequestMessage
        WS_MESSAGE_DESCRIPTION CloseServiceRequestMessage;
        
        // message: CloseServiceResponseMessage
        // c type: _CloseServiceResponse
        // action: ""
        // messageDescription: MacStatsCollection_wsdl.messages.CloseServiceResponseMessage
        WS_MESSAGE_DESCRIPTION CloseServiceResponseMessage;
        
    } messages;
    struct // contracts
    {
        // binding: MacStatsCollectionBinding
        // portType: MacStatsCollectionInterface
        // operation: MacStatsCollectionBinding_SendStatsSample
        //     input message: SendStatsSampleRequestMessage
        //     output message: SendStatsSampleResponseMessage
        // operation: MacStatsCollectionBinding_CloseService
        //     input message: CloseServiceRequestMessage
        //     output message: CloseServiceResponseMessage
        // contractDescription: MacStatsCollection_wsdl.contracts.MacStatsCollectionBinding
        WS_CONTRACT_DESCRIPTION MacStatsCollectionBinding;
        
    } contracts;
    struct // policies
    {
        // policy for binding: MacStatsCollectionBinding
        // port name: MacStatsCollectionEndpoint, binding: MacStatsCollectionBinding, namespace: http://assignment.crossover.com/
        WS_HTTP_POLICY_DESCRIPTION MacStatsCollectionBinding;
    } policies;
} _MacStatsCollection_wsdl;

extern const _MacStatsCollection_wsdl MacStatsCollection_wsdl;

#ifdef __cplusplus
}
#endif

