
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "MacStatsCollection.wsdl.h"

typedef struct _MacStatsCollection_wsdlLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // listOfStatsFloat32
        {
            struct  // listOfStatsFloat32_entry
            {
                WS_FIELD_DESCRIPTION statName;
                WS_FIELD_DESCRIPTION statValue;
                WS_FIELD_DESCRIPTION quality;
                WS_FIELD_DESCRIPTION* listOfStatsFloat32_entryFields [3]; 
                WS_STRUCT_DESCRIPTION structDesc;
            } listOfStatsFloat32_entrydescs; // end of listOfStatsFloat32_entry
            WS_ITEM_RANGE _entryRangeDesc;
            WS_FIELD_DESCRIPTION entry;
            WS_FIELD_DESCRIPTION* listOfStatsFloat32Fields [1]; 
        } listOfStatsFloat32descs; // end of listOfStatsFloat32
        struct  // listOfStatsInt32
        {
            struct  // listOfStatsInt32_entry
            {
                WS_FIELD_DESCRIPTION statName;
                WS_FIELD_DESCRIPTION statValue;
                WS_FIELD_DESCRIPTION quality;
                WS_FIELD_DESCRIPTION* listOfStatsInt32_entryFields [3]; 
                WS_STRUCT_DESCRIPTION structDesc;
            } listOfStatsInt32_entrydescs; // end of listOfStatsInt32_entry
            WS_ITEM_RANGE _entryRangeDesc;
            WS_FIELD_DESCRIPTION entry;
            WS_FIELD_DESCRIPTION* listOfStatsInt32Fields [1]; 
        } listOfStatsInt32descs; // end of listOfStatsInt32
        struct  // SendStatsSampleRequest
        {
            WS_FIELD_DESCRIPTION time;
            WS_FIELD_DESCRIPTION machine;
            WS_ITEM_RANGE _statsFloat32RangeDesc;
            WS_FIELD_DESCRIPTION statsFloat32;
            WS_ITEM_RANGE _statsInt32RangeDesc;
            WS_FIELD_DESCRIPTION statsInt32;
            WS_FIELD_DESCRIPTION* SendStatsSampleRequestFields [4]; 
        } SendStatsSampleRequestdescs; // end of SendStatsSampleRequest
    } globalTypes;  // end of global types
    struct  // global elements
    {
    char unused;
        struct  // _WrapSendStatsSampleRequest
        {
            WS_FIELD_DESCRIPTION key;
            WS_FIELD_DESCRIPTION payload;
            WS_FIELD_DESCRIPTION* _WrapSendStatsSampleRequestFields [2]; 
        } _WrapSendStatsSampleRequestdescs; // end of _WrapSendStatsSampleRequest
        struct  // _SendStatsSampleResponse
        {
            WS_FIELD_DESCRIPTION status;
            WS_FIELD_DESCRIPTION* _SendStatsSampleResponseFields [1]; 
        } _SendStatsSampleResponsedescs; // end of _SendStatsSampleResponse
        struct  // _CloseServiceResponse
        {
            WS_FIELD_DESCRIPTION status;
            WS_FIELD_DESCRIPTION* _CloseServiceResponseFields [1]; 
        } _CloseServiceResponsedescs; // end of _CloseServiceResponse
    } globalElements;  // end of global elements
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION SendStatsSampleRequestMessage;
        WS_MESSAGE_DESCRIPTION SendStatsSampleResponseMessage;
        WS_MESSAGE_DESCRIPTION CloseServiceRequestMessage;
        WS_MESSAGE_DESCRIPTION CloseServiceResponseMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // MacStatsCollectionBinding
        {
            struct  // MacStatsCollectionBinding_SendStatsSample
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION MacStatsCollectionBinding_SendStatsSample;
            } MacStatsCollectionBinding_SendStatsSample;
            struct  // MacStatsCollectionBinding_CloseService
            {
                WS_PARAMETER_DESCRIPTION params[1];
                WS_OPERATION_DESCRIPTION MacStatsCollectionBinding_CloseService;
            } MacStatsCollectionBinding_CloseService;
            WS_OPERATION_DESCRIPTION* operations[2];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } MacStatsCollectionBinding;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // MacStatsCollectionBinding
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } MacStatsCollectionBinding;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING listOfStatsFloat32TypeName;  // listOfStatsFloat32
            WS_XML_STRING listOfStatsFloat32TypeNamespace;  // http://assignment.crossover.com/
            WS_XML_STRING listOfStatsFloat32_entryTypeName;  // entry
            WS_XML_STRING listOfStatsFloat32_entrystatNameLocalName;  // statName
            WS_XML_STRING listOfStatsFloat32_entrystatNameNamespace;  // 
            WS_XML_STRING listOfStatsFloat32_entrystatValueLocalName;  // statValue
            WS_XML_STRING listOfStatsFloat32_entryqualityLocalName;  // quality
            WS_XML_STRING listOfStatsInt32TypeName;  // listOfStatsInt32
            WS_XML_STRING SendStatsSampleRequestTypeName;  // SendStatsSampleRequest
            WS_XML_STRING SendStatsSampleRequesttimeLocalName;  // time
            WS_XML_STRING SendStatsSampleRequestmachineLocalName;  // machine
            WS_XML_STRING SendStatsSampleRequeststatsFloat32WrapperName;  // statsFloat32
            WS_XML_STRING SendStatsSampleRequeststatsInt32WrapperName;  // statsInt32
            WS_XML_STRING _WrapSendStatsSampleRequestTypeName;  // WrapSendStatsSampleRequest
            WS_XML_STRING _WrapSendStatsSampleRequestkeyLocalName;  // key
            WS_XML_STRING _WrapSendStatsSampleRequestpayloadLocalName;  // payload
            WS_XML_STRING _SendStatsSampleResponseTypeName;  // SendStatsSampleResponse
            WS_XML_STRING _SendStatsSampleResponsestatusLocalName;  // status
            WS_XML_STRING _CloseServiceRequestTypeName;  // CloseServiceRequest
            WS_XML_STRING _CloseServiceResponseTypeName;  // CloseServiceResponse
            WS_XML_STRING SendStatsSampleRequestMessageactionName;  // http://assignment.crossover.com/SendStatsSample
            WS_XML_STRING CloseServiceRequestMessageactionName;  // http://assignment.crossover.com/CloseService
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _MacStatsCollection_wsdlLocalDefinitions;


typedef struct MacStatsCollectionBinding_SendStatsSampleParamStruct 
{
    WCHAR** key;
    SendStatsSampleRequest** payload;
    BOOL* status;
} MacStatsCollectionBinding_SendStatsSampleParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK MacStatsCollectionBinding_SendStatsSampleOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    MacStatsCollectionBinding_SendStatsSampleCallback _operation = (MacStatsCollectionBinding_SendStatsSampleCallback)_callback;
    MacStatsCollectionBinding_SendStatsSampleParamStruct *_stack =(MacStatsCollectionBinding_SendStatsSampleParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->key),
        *(_stack->payload),
        (_stack->status),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct MacStatsCollectionBinding_CloseServiceParamStruct 
{
    BOOL* status;
} MacStatsCollectionBinding_CloseServiceParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK MacStatsCollectionBinding_CloseServiceOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    MacStatsCollectionBinding_CloseServiceCallback _operation = (MacStatsCollectionBinding_CloseServiceCallback)_callback;
    MacStatsCollectionBinding_CloseServiceParamStruct *_stack =(MacStatsCollectionBinding_CloseServiceParamStruct*)_stackStruct;
    return _operation( 
        _context,
        (_stack->status),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _MacStatsCollection_wsdlLocalDefinitions MacStatsCollection_wsdlLocalDefinitions =
{
    { // global types
        0,
        {  // listOfStatsFloat32
            {  // listOfStatsFloat32_entry
                {  // field description for statName
                WS_ATTRIBUTE_FIELD_MAPPING,
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatNameLocalName, // statName
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatNameNamespace, // 
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(listOfStatsFloat32_entry, statName),
                0,
                0,
                0xffffffff
                },    // end of field description for statName
                {  // field description for statValue
                WS_ATTRIBUTE_FIELD_MAPPING,
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatValueLocalName, // statValue
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatNameNamespace, // 
                WS_FLOAT_TYPE,
                0,
                WsOffsetOf(listOfStatsFloat32_entry, statValue),
                0,
                0,
                0xffffffff
                },    // end of field description for statValue
                {  // field description for quality
                WS_ATTRIBUTE_FIELD_MAPPING,
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entryqualityLocalName, // quality
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatNameNamespace, // 
                WS_INT8_TYPE,
                0,
                WsOffsetOf(listOfStatsFloat32_entry, quality),
                0,
                0,
                0xffffffff
                },    // end of field description for quality
                {  // fields description for listOfStatsFloat32_entry
                (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32_entrydescs.statName,
                (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32_entrydescs.statValue,
                (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32_entrydescs.quality,
                },
                {
                sizeof(listOfStatsFloat32_entry),
                __alignof(listOfStatsFloat32_entry),
                (WS_FIELD_DESCRIPTION**)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32_entrydescs.listOfStatsFloat32_entryFields,
                WsCountOf(MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32_entrydescs.listOfStatsFloat32_entryFields),
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entryTypeName, // entry
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
                0,
                0,
                0,
                },   // end of struct description for listOfStatsFloat32_entry
            },    // listOfStatsFloat32_entry
            {1, 4294967295},
            {  // field description for entry
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32_entrydescs.structDesc,
            WsOffsetOf(listOfStatsFloat32, entry),
            0,
            0,
            WsOffsetOf(listOfStatsFloat32, entryCount),
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entryTypeName, // entry
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            (WS_ITEM_RANGE*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs._entryRangeDesc,
            },    // end of field description for entry
            {  // fields description for listOfStatsFloat32
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.entry,
            },
        },    // listOfStatsFloat32
        {  // listOfStatsInt32
            {  // listOfStatsInt32_entry
                {  // field description for statName
                WS_ATTRIBUTE_FIELD_MAPPING,
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatNameLocalName, // statName
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatNameNamespace, // 
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(listOfStatsInt32_entry, statName),
                0,
                0,
                0xffffffff
                },    // end of field description for statName
                {  // field description for statValue
                WS_ATTRIBUTE_FIELD_MAPPING,
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatValueLocalName, // statValue
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatNameNamespace, // 
                WS_INT32_TYPE,
                0,
                WsOffsetOf(listOfStatsInt32_entry, statValue),
                0,
                0,
                0xffffffff
                },    // end of field description for statValue
                {  // field description for quality
                WS_ATTRIBUTE_FIELD_MAPPING,
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entryqualityLocalName, // quality
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entrystatNameNamespace, // 
                WS_INT8_TYPE,
                0,
                WsOffsetOf(listOfStatsInt32_entry, quality),
                0,
                0,
                0xffffffff
                },    // end of field description for quality
                {  // fields description for listOfStatsInt32_entry
                (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32_entrydescs.statName,
                (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32_entrydescs.statValue,
                (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32_entrydescs.quality,
                },
                {
                sizeof(listOfStatsInt32_entry),
                __alignof(listOfStatsInt32_entry),
                (WS_FIELD_DESCRIPTION**)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32_entrydescs.listOfStatsInt32_entryFields,
                WsCountOf(MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32_entrydescs.listOfStatsInt32_entryFields),
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entryTypeName, // entry
                (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
                0,
                0,
                0,
                },   // end of struct description for listOfStatsInt32_entry
            },    // listOfStatsInt32_entry
            {1, 4294967295},
            {  // field description for entry
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32_entrydescs.structDesc,
            WsOffsetOf(listOfStatsInt32, entry),
            0,
            0,
            WsOffsetOf(listOfStatsInt32, entryCount),
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entryTypeName, // entry
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            (WS_ITEM_RANGE*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs._entryRangeDesc,
            },    // end of field description for entry
            {  // fields description for listOfStatsInt32
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.entry,
            },
        },    // listOfStatsInt32
        {  // SendStatsSampleRequest
            {  // field description for time
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.SendStatsSampleRequesttimeLocalName, // time
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_INT64_TYPE,
            0,
            WsOffsetOf(SendStatsSampleRequest, time),
            0,
            0,
            0xffffffff
            },    // end of field description for time
            {  // field description for machine
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.SendStatsSampleRequestmachineLocalName, // machine
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(SendStatsSampleRequest, machine),
            0,
            0,
            0xffffffff
            },    // end of field description for machine
            {1, 4294967295},
            {  // field description for statsFloat32
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.SendStatsSampleRequeststatsFloat32WrapperName, // statsFloat32
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32_entrydescs.structDesc,
            WsOffsetOf(SendStatsSampleRequest, statsFloat32),
            0,
            0,
            WsOffsetOf(SendStatsSampleRequest, statsFloat32Count),
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entryTypeName, // entry
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            (WS_ITEM_RANGE*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.SendStatsSampleRequestdescs._statsFloat32RangeDesc,
            },    // end of field description for statsFloat32
            {1, 4294967295},
            {  // field description for statsInt32
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.SendStatsSampleRequeststatsInt32WrapperName, // statsInt32
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32_entrydescs.structDesc,
            WsOffsetOf(SendStatsSampleRequest, statsInt32),
            0,
            0,
            WsOffsetOf(SendStatsSampleRequest, statsInt32Count),
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32_entryTypeName, // entry
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            (WS_ITEM_RANGE*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.SendStatsSampleRequestdescs._statsInt32RangeDesc,
            },    // end of field description for statsInt32
            {  // fields description for SendStatsSampleRequest
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.SendStatsSampleRequestdescs.time,
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.SendStatsSampleRequestdescs.machine,
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.SendStatsSampleRequestdescs.statsFloat32,
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.SendStatsSampleRequestdescs.statsInt32,
            },
        },    // SendStatsSampleRequest
    }, // end of global types
    {  // global elements
        0,
        {  // _WrapSendStatsSampleRequest
            {  // field description for key
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._WrapSendStatsSampleRequestkeyLocalName, // key
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_WrapSendStatsSampleRequest, key),
            0,
            0,
            0xffffffff
            },    // end of field description for key
            {  // field description for payload
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._WrapSendStatsSampleRequestpayloadLocalName, // payload
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdl.globalTypes.SendStatsSampleRequest,
            WsOffsetOf(_WrapSendStatsSampleRequest, payload),
            WS_FIELD_POINTER,
            0,
            0xffffffff
            },    // end of field description for payload
            {  // fields description for _WrapSendStatsSampleRequest
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalElements._WrapSendStatsSampleRequestdescs.key,
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalElements._WrapSendStatsSampleRequestdescs.payload,
            },
        },    // _WrapSendStatsSampleRequest
        {  // _SendStatsSampleResponse
            {  // field description for status
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._SendStatsSampleResponsestatusLocalName, // status
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_SendStatsSampleResponse, status),
            0,
            0,
            0xffffffff
            },    // end of field description for status
            {  // fields description for _SendStatsSampleResponse
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalElements._SendStatsSampleResponsedescs.status,
            },
        },    // _SendStatsSampleResponse
        {  // _CloseServiceResponse
            {  // field description for status
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._SendStatsSampleResponsestatusLocalName, // status
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_CloseServiceResponse, status),
            0,
            0,
            0xffffffff
            },    // end of field description for status
            {  // fields description for _CloseServiceResponse
            (WS_FIELD_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.globalElements._CloseServiceResponsedescs.status,
            },
        },    // _CloseServiceResponse
    }, // end of global elements
    {  // messages
        {  // message description for SendStatsSampleRequestMessage
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.SendStatsSampleRequestMessageactionName, // http://assignment.crossover.com/SendStatsSample
            (WS_ELEMENT_DESCRIPTION*)&MacStatsCollection_wsdl.globalElements.WrapSendStatsSampleRequest, 
        },    // message description for SendStatsSampleRequestMessage
        {  // message description for SendStatsSampleResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&MacStatsCollection_wsdl.globalElements.SendStatsSampleResponse, 
        },    // message description for SendStatsSampleResponseMessage
        {  // message description for CloseServiceRequestMessage
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.CloseServiceRequestMessageactionName, // http://assignment.crossover.com/CloseService
            (WS_ELEMENT_DESCRIPTION*)&MacStatsCollection_wsdl.globalElements.CloseServiceRequest, 
        },    // message description for CloseServiceRequestMessage
        {  // message description for CloseServiceResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&MacStatsCollection_wsdl.globalElements.CloseServiceResponse, 
        },    // message description for CloseServiceResponseMessage
    },  // end of messages 
    {  // contracts
        {  // MacStatsCollectionBinding,
            {  // MacStatsCollectionBinding_SendStatsSample
                {  // parameter descriptions for MacStatsCollectionBinding_SendStatsSample
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for MacStatsCollectionBinding_SendStatsSample
                {  // operation description for MacStatsCollectionBinding_SendStatsSample
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&MacStatsCollection_wsdl.messages.SendStatsSampleRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&MacStatsCollection_wsdl.messages.SendStatsSampleResponseMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)MacStatsCollection_wsdlLocalDefinitions.contracts.MacStatsCollectionBinding.MacStatsCollectionBinding_SendStatsSample.params,
                    MacStatsCollectionBinding_SendStatsSampleOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for MacStatsCollectionBinding_SendStatsSample
            },  // MacStatsCollectionBinding_SendStatsSample
            {  // MacStatsCollectionBinding_CloseService
                {  // parameter descriptions for MacStatsCollectionBinding_CloseService
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for MacStatsCollectionBinding_CloseService
                {  // operation description for MacStatsCollectionBinding_CloseService
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&MacStatsCollection_wsdl.messages.CloseServiceRequestMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&MacStatsCollection_wsdl.messages.CloseServiceResponseMessage, 
                    0,
                    0,
                    1,
                    (WS_PARAMETER_DESCRIPTION*)MacStatsCollection_wsdlLocalDefinitions.contracts.MacStatsCollectionBinding.MacStatsCollectionBinding_CloseService.params,
                    MacStatsCollectionBinding_CloseServiceOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for MacStatsCollectionBinding_CloseService
            },  // MacStatsCollectionBinding_CloseService
            {  // array of operations for MacStatsCollectionBinding
                (WS_OPERATION_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.contracts.MacStatsCollectionBinding.MacStatsCollectionBinding_SendStatsSample.MacStatsCollectionBinding_SendStatsSample,
                (WS_OPERATION_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.contracts.MacStatsCollectionBinding.MacStatsCollectionBinding_CloseService.MacStatsCollectionBinding_CloseService,
            },  // array of operations for MacStatsCollectionBinding
            {  // contract description for MacStatsCollectionBinding
            2,
            (WS_OPERATION_DESCRIPTION**)MacStatsCollection_wsdlLocalDefinitions.contracts.MacStatsCollectionBinding.operations,
            },  // end of contract description for MacStatsCollectionBinding
        },  // MacStatsCollectionBinding
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_2,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&MacStatsCollection_wsdlLocalDefinitions.policies.MacStatsCollectionBinding.encoding,
                    sizeof(MacStatsCollection_wsdlLocalDefinitions.policies.MacStatsCollectionBinding.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&MacStatsCollection_wsdlLocalDefinitions.policies.MacStatsCollectionBinding.addressingVersion,
                    sizeof(MacStatsCollection_wsdlLocalDefinitions.policies.MacStatsCollectionBinding.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&MacStatsCollection_wsdlLocalDefinitions.policies.MacStatsCollectionBinding.envelopeVersion,
                    sizeof(MacStatsCollection_wsdlLocalDefinitions.policies.MacStatsCollectionBinding.envelopeVersion),
                },
            },
        },   // end of MacStatsCollectionBinding,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("listOfStatsFloat32",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://assignment.crossover.com/",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("entry",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("statName",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("statValue",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("quality",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("listOfStatsInt32",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("SendStatsSampleRequest",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("time",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("machine",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("statsFloat32",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("statsInt32",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("WrapSendStatsSampleRequest",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("key",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("payload",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("SendStatsSampleResponse",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("status",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("CloseServiceRequest",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("CloseServiceResponse",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("http://assignment.crossover.com/SendStatsSample",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("http://assignment.crossover.com/CloseService",&MacStatsCollection_wsdlLocalDefinitions.dictionary.dict, 21),
        },  // end of xmlStrings
        
        {  // MacStatsCollection_wsdldictionary
          // 0922d2a0-e9ae-415b-8898-e16dd9443ad8 
        { 0x0922d2a0, 0xe9ae, 0x415b, { 0x88, 0x98, 0xe1,0x6d, 0xd9, 0x44, 0x3a, 0xd8 } },
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings,
        22,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of MacStatsCollection_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: MacStatsCollectionBinding_SendStatsSample
HRESULT WINAPI MacStatsCollectionBinding_SendStatsSample(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_z_ WCHAR* key, 
    _In_ SendStatsSampleRequest* payload, 
    _Out_ BOOL* status, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &key;
    _argList[1] = &payload;
    _argList[2] = &status;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.contracts.MacStatsCollectionBinding.MacStatsCollectionBinding_SendStatsSample.MacStatsCollectionBinding_SendStatsSample,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: MacStatsCollectionBinding_CloseService
HRESULT WINAPI MacStatsCollectionBinding_CloseService(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Out_ BOOL* status, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[1]; 
    _argList[0] = &status;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&MacStatsCollection_wsdlLocalDefinitions.contracts.MacStatsCollectionBinding.MacStatsCollectionBinding_CloseService.MacStatsCollectionBinding_CloseService,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _MacStatsCollection_wsdl MacStatsCollection_wsdl =
{
    {  // globalTypes
        {
        sizeof(listOfStatsFloat32),
        __alignof(listOfStatsFloat32),
        (WS_FIELD_DESCRIPTION**)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32Fields,
        WsCountOf(MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsFloat32descs.listOfStatsFloat32Fields),
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeName, // listOfStatsFloat32
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
        0,
        0,
        0,
        },   // end of struct description for listOfStatsFloat32
        {
        sizeof(listOfStatsInt32),
        __alignof(listOfStatsInt32),
        (WS_FIELD_DESCRIPTION**)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32Fields,
        WsCountOf(MacStatsCollection_wsdlLocalDefinitions.globalTypes.listOfStatsInt32descs.listOfStatsInt32Fields),
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsInt32TypeName, // listOfStatsInt32
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
        0,
        0,
        0,
        },   // end of struct description for listOfStatsInt32
        {
        sizeof(SendStatsSampleRequest),
        __alignof(SendStatsSampleRequest),
        (WS_FIELD_DESCRIPTION**)&MacStatsCollection_wsdlLocalDefinitions.globalTypes.SendStatsSampleRequestdescs.SendStatsSampleRequestFields,
        WsCountOf(MacStatsCollection_wsdlLocalDefinitions.globalTypes.SendStatsSampleRequestdescs.SendStatsSampleRequestFields),
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.SendStatsSampleRequestTypeName, // SendStatsSampleRequest
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
        0,
        0,
        0,
        },   // end of struct description for SendStatsSampleRequest
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._WrapSendStatsSampleRequestTypeName, // WrapSendStatsSampleRequest
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdl.externallyReferencedTypes.WrapSendStatsSampleRequest,
        },
        {
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._SendStatsSampleResponseTypeName, // SendStatsSampleResponse
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdl.externallyReferencedTypes.SendStatsSampleResponse,
        },
        {
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._CloseServiceRequestTypeName, // CloseServiceRequest
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdl.externallyReferencedTypes.CloseServiceRequest,
        },
        {
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._CloseServiceResponseTypeName, // CloseServiceResponse
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
            WS_STRUCT_TYPE,
            (void*)&MacStatsCollection_wsdl.externallyReferencedTypes.CloseServiceResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_WrapSendStatsSampleRequest),
        __alignof(_WrapSendStatsSampleRequest),
        (WS_FIELD_DESCRIPTION**)&MacStatsCollection_wsdlLocalDefinitions.globalElements._WrapSendStatsSampleRequestdescs._WrapSendStatsSampleRequestFields,
        WsCountOf(MacStatsCollection_wsdlLocalDefinitions.globalElements._WrapSendStatsSampleRequestdescs._WrapSendStatsSampleRequestFields),
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._WrapSendStatsSampleRequestTypeName, // WrapSendStatsSampleRequest
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
        0,
        0,
        0,
        },   // end of struct description for _WrapSendStatsSampleRequest
        {
        sizeof(_SendStatsSampleResponse),
        __alignof(_SendStatsSampleResponse),
        (WS_FIELD_DESCRIPTION**)&MacStatsCollection_wsdlLocalDefinitions.globalElements._SendStatsSampleResponsedescs._SendStatsSampleResponseFields,
        WsCountOf(MacStatsCollection_wsdlLocalDefinitions.globalElements._SendStatsSampleResponsedescs._SendStatsSampleResponseFields),
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._SendStatsSampleResponseTypeName, // SendStatsSampleResponse
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
        0,
        0,
        0,
        },   // end of struct description for _SendStatsSampleResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._CloseServiceRequestTypeName, // CloseServiceRequest
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
        0,
        0,
        0,
        },   // end of struct description for _CloseServiceRequest
        {
        sizeof(_CloseServiceResponse),
        __alignof(_CloseServiceResponse),
        (WS_FIELD_DESCRIPTION**)&MacStatsCollection_wsdlLocalDefinitions.globalElements._CloseServiceResponsedescs._CloseServiceResponseFields,
        WsCountOf(MacStatsCollection_wsdlLocalDefinitions.globalElements._CloseServiceResponsedescs._CloseServiceResponseFields),
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings._CloseServiceResponseTypeName, // CloseServiceResponse
        (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.listOfStatsFloat32TypeNamespace, // http://assignment.crossover.com/
        0,
        0,
        0,
        },   // end of struct description for _CloseServiceResponse
    },  // end of externallyReferencedTypes;
    {  // messages
        {  // message description for SendStatsSampleRequestMessage
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.SendStatsSampleRequestMessageactionName, // http://assignment.crossover.com/SendStatsSample
            (WS_ELEMENT_DESCRIPTION*)&MacStatsCollection_wsdl.globalElements.WrapSendStatsSampleRequest, 
        },    // message description for SendStatsSampleRequestMessage
        {  // message description for SendStatsSampleResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&MacStatsCollection_wsdl.globalElements.SendStatsSampleResponse, 
        },    // message description for SendStatsSampleResponseMessage
        {  // message description for CloseServiceRequestMessage
            (WS_XML_STRING*)&MacStatsCollection_wsdlLocalDefinitions.dictionary.xmlStrings.CloseServiceRequestMessageactionName, // http://assignment.crossover.com/CloseService
            (WS_ELEMENT_DESCRIPTION*)&MacStatsCollection_wsdl.globalElements.CloseServiceRequest, 
        },    // message description for CloseServiceRequestMessage
        {  // message description for CloseServiceResponseMessage
            0,
            (WS_ELEMENT_DESCRIPTION*)&MacStatsCollection_wsdl.globalElements.CloseServiceResponse, 
        },    // message description for CloseServiceResponseMessage
    },  // messages
    {  // contracts
        {  // MacStatsCollectionBinding
            2,
            (WS_OPERATION_DESCRIPTION**)MacStatsCollection_wsdlLocalDefinitions.contracts.MacStatsCollectionBinding.operations,
        },  // end of MacStatsCollectionBinding
    },  // contracts
    {  // policies
        {  // template description for MacStatsCollectionBinding
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&MacStatsCollection_wsdlLocalDefinitions.policies.MacStatsCollectionBinding.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _MacStatsCollection_wsdl

HRESULT MacStatsCollectionBinding_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &MacStatsCollection_wsdl.policies.MacStatsCollectionBinding,
        sizeof(MacStatsCollection_wsdl.policies.MacStatsCollectionBinding),
        _serviceProxy,
        error);
}

HRESULT MacStatsCollectionBinding_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct MacStatsCollectionBindingFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &MacStatsCollection_wsdl.contracts.MacStatsCollectionBinding;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &MacStatsCollection_wsdl.policies.MacStatsCollectionBinding,
        sizeof(MacStatsCollection_wsdl.policies.MacStatsCollectionBinding),
        serviceEndpoint,
        error);
}
